---
name: Release

on: push

jobs:
  macos-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Read version to environment
        run: echo "VERSION=$(cat resources/POD_ILMORAUNIO_CLJCONF)" >> $GITHUB_ENV
      - name: Install babashka
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          bb: 1.3.190
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.1'
      - name: Initialize submodules
        run: git submodule update --init --recursive
      - name: Debug
        run: go version && uname -a
      - name: Install pod-ilmoraunio-conftest deps
        run: cd pod-ilmoraunio-conftest && go install
      - name: Build pod-ilmoraunio-conftest binary
        run: cd pod-ilmoraunio-conftest && go build
      - name: Build uberjar
        run: bb uberjar target/pod-ilmoraunio-cljconf.jar -m pod-ilmoraunio-cljconf.core
      - name: Build binary
        run: cat $(which bb) target/pod-ilmoraunio-cljconf.jar > pod-ilmoraunio-cljconf && chmod +x pod-ilmoraunio-cljconf
      - name: Test build
        run: ./scripts/test
      - name: Debug
        run: ls -lart
      - name: Produce artifact
        run: zip pod-ilmoraunio-cljconf-$VERSION-macos-aarch64.zip pod-ilmoraunio-cljconf
      - name: Release artifact
        run: bb --config bb.ci.edn release-artifact --file pod-ilmoraunio-cljconf-$VERSION-macos-aarch64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Read version to environment
        run: echo "VERSION=$(cat resources/POD_ILMORAUNIO_CLJCONF)" >> $GITHUB_ENV
      - name: Install babashka
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          bb: 1.3.190
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.1'
      - name: Initialize submodules
        run: git submodule update --init --recursive
      - name: Debug
        run: go version && uname -a
      - name: Install pod-ilmoraunio-conftest deps
        run: cd pod-ilmoraunio-conftest && go install
      - name: Build pod-ilmoraunio-conftest binary
        run: cd pod-ilmoraunio-conftest && go build
      - name: Build uberjar
        run: bb uberjar target/pod-ilmoraunio-cljconf.jar -m pod-ilmoraunio-cljconf.core
      - name: Build binary
        run: cat $(which bb) target/pod-ilmoraunio-cljconf.jar > pod-ilmoraunio-cljconf && chmod +x pod-ilmoraunio-cljconf
      - name: Test build
        run: ./scripts/test
      - name: Debug
        run: ls -lart
      - name: Produce artifact
        run: zip pod-ilmoraunio-cljconf-$VERSION-linux-amd64.zip pod-ilmoraunio-cljconf
      - name: Release artifact
        run: bb --config bb.ci.edn release-artifact --file pod-ilmoraunio-cljconf-$VERSION-linux-amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
